---
name: lint

on:
  push:
  pull_request:

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.3
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: development
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - run: bundle exec rubocop --parallel --fail-level E
